import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Games Kingdom',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png"/>
        <link rel="manifest" href="img/site.webmanifest"/>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
